spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  main:
    banner-mode: "off"
  application:
    name: backendtask
  datasource:
    url: jdbc:postgresql://db:5432/seriousdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate   # NEVER create/update with Hibernate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 10030
  error:
    include-stacktrace: never

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration: 3600000  # 1 hour

serious-app:
  superadmin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}